language: node_js
node_js:
- '0.12'

sudo: false
cache: node_modules

env:
  global:
  - export LC_CTYPE=ja_JP.UTF-8
  - GIT_COMMITTER_NAME=kubosho_
  - GIT_COMMITTER_EMAIL=ta2@o2p.jp
  - GIT_AUTHOR_NAME=kubosho_
  - GIT_AUTHOR_EMAIL=ta2@o2p.jp
  - secure: p5FOswxHmmbfoNRQ9Y0WDn+ABIljtUY4hLDfDTxndWR9EKfjEEBSN7SWv/lvgRZwLdW16gffT/1kF0T5LtbRF5MRs08NIfjJdVNr9DLbkmYAtHD5ymWCH3hGOj/nH7NB5hSWgp8kwmprS1NrvuTlgxC4hEkXFL5YWY5nJ669uRRpm0NFhR41f7/JszYrv0/GHE5f6gQBzyj+QwfjUE4J3E8YFLXmtowmUo2j30szkxSQAVDv6whK0p47xNJWlCvG40TYhocsPCIMo9G9CT0/p21F6SpNJ9lxR0czFPsW4xOva8SVVQU2bpDP5YG19YBGnV9qsvw//sXW1/l7wc5fnBdXOomK4rirf0IklQarSw68Hi9iIDnsJgC2hULF90UpYYkVYwm4LIm2u0Q4zxLANBULV1YJkdwrFCm7ZDV/hHagSbx9l9UdiGlvfAWC7RqmSNESkyOdk0RDS4GTX5MBTRw7EBrb7Yp/CZARPhXqoUfO+Ol7CYONV+n6YpqADsVHWgVee4Ds5Pd1dfSaBPqbvjHHTF/2Ptzq96Wfxn4MHeASiiKlTBbDK/qQp7sCxiggS14MO3cEcclzjjsoNKlKknbn/jTdMyC7DyqGREZz9VLFCzPZyuzetGAeNyZ+4i+ym7IB7vLmGvyR388+ppp9BLnygmgayt0tMd81dhI8/R0=

git:
  submodules: false

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init src/bootstrap
- gem install compass

script:
- npm start

after_success:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [
  "$GH_TOKEN" ] && ./.bin/deploy-to-gh-pages.sh > /dev/null'
